version: '3'
services:
  php:
    build:
      context: .
      dockerfile: dockerfile
    image: cafernandes/composer-php-test
    container_name: php-design-pattern
    ports:
      - '8080:8080'
    volumes:
      - .:/app
